'''
games = {
    "minecraft": "A block-building survival and crafting sandbox game.",
    "roblox": "A platform with millions of user-created games.",
    "fortnite": "A battle-royale game with building mechanics.",
    "pubg": "A realistic battle-royale FPS game.",
    "freefire": "A fast-paced mobile battle-royale shooter.",
    "amongus": "A social deduction game with crewmates and impostors.",
    "subwaysurfers": "An endless runner game where you dodge trains.",
    "templerun": "Run from monsters in an ancient temple.",
    "candycrush": "Match-3 puzzle game with candies.",
    "clashofclans": "Build a village and attack others with troops.",
    "clashroyale": "Real-time strategy card battle game.",
    "bgmi": "Indian version of PUBG Mobile.",
    "asphalt9": "High-speed arcade racing game.",
    "gta5": "Open-world crime and adventure game.",
    "gtasanandreas": "Popular open-world city crime game.",
    "genshinimpact": "Anime-style open-world RPG.",
    "valorant": "Tactical 5v5 shooter with abilities.",
    "callofduty": "A very popular FPS war game series.",
    "godofwar": "Action game about Kratos and Norse gods.",
    "spiderman": "Swing through a city as a superhero.",
    "pokemon": "Catch and battle creatures called Pokémon.",
    "brawlstars": "Fast-paced 3v3 multiplayer shooter.",
    "standoff2": "Mobile competitive shooting game.",
    "fallguys": "Funny mini-game battle-royale.",
    "fifa": "A football (soccer) simulation game.",
    "pes": "Popular football simulation game.",
    "realcricket": "One of the top cricket games on mobile.",
    "ludoking": "Digital version of the classic Ludo board game.",
    "carrompool": "Carrom board game played online.",
    "8ballpool": "One of the most famous online pool games.",
    "hillclimbracing": "Climb hills with physics-based vehicles.",
    "flappybird": "Tap to fly the bird without hitting pipes.",
    "angrybirds": "Launch birds to destroy pig structures.",
    "plantsvszombies": "Defend your home from zombies using plants.",
    "tetris": "Classic block-fitting puzzle game.",
    "pacman": "Eat pellets and avoid ghosts in a maze.",
    "chess": "Classic strategy board game.",
    "monopoly": "Buy property and make opponents go bankrupt.",
    "terraria": "2D sandbox survival and exploration game.",
    "stardewvalley": "Farming and village life simulator.",
    "rocketleague": "Football played with rocket-powered cars.",
    "apexlegends": "Fast-paced hero-based battle-royale.",
    "counterstrike": "Classic FPS terrorists vs counter-terrorists.",
    "overwatch": "Hero shooter with unique abilities.",
    "dota2": "5v5 MOBA strategy game on a big map.",
    "leagueoflegends": "Popular MOBA with champions and lanes.",
    "fortnitecreative": "Build and create your own maps in Fortnite.",
    "supermario": "Classic platform game starring Mario."
}
'''
games= (
    "minecraft","roblox","fortnite","pubg","freefire","callofduty","valorant","apexlegends",
    "counterstrike","overwatch","leagueoflegends","dota2","genshinimpact","pokemon","fallguys",
    "amongus","clashofclans","clashroyale","candycrush","subwaysurfers","templerun","asphalt9",
    "fifa","pes","nba2k","wwe2k","mariokart","supermario","sonic","zelda","mariobros",
    "pokemonunite","brawlstars","standoff2","garena","bgmi","nfsheat","nfspayback","nfsmw",
    "battlefield","halo","gears5","doom","skyrim","fallout","thewitcher","eldenring","dark souls",
    "bloodborne","sekiro","tekken","streetfighter","mortalcombat","injustice2","forza",
    "gran turismo","cyberpunk2077","reddead2","gta5","gtavicecity","gtasanandreas","farcry5",
    "farcry6","justcause","hitman","splintercell","watchdogs","bioshock","deadspace",
    "assassinscreed","creedvalhalla","creedorigins","middleearth","shadowofwar","shadowofmordor",
    "residentevil2","residentevil4","residentevil7","residentevilvillage","outlast","amnesia",
    "little nightmares","uncharted","tombraider","metalgear","mass effect","dragonage",
    "horizonzerodawn","horizonforbiddenwest","godofwar","godofwarragnarok","spidermanps4",
    "spidermanmiles","ratchetclank","deadbydaylight","dyinglight","dyinglight2","rust","ark",
    "terraria","stardewvalley","limbo","inside","hollowknight","cultofthelamb","cuphead",
    "undertale","deltarune","celeste","oriandtheblindforest","oriandthewillwisps",
    "dontstarve","bendyandinkmachine","five nightsatfreddys","plantsvszombies","pvzheroes",
    "pvzgardenwarfare","angrybirds","angrybirdsepic","angrybirdsrio","legoavengers","legobatman",
    "legomarvel","legojurassic","legocity","legohobbit","legoindianajones",
    "tetris","pacman","snake","spaceinvaders","galaga","pong","kof","contra","metalslug",
    "princeofpersia","shadowfight2","shadowfight3","shadowfightarena","monumentvalley",
    "monumentvalley2","badland","badland2","jetpackjoyride","skateboardparty","realcricket",
    "wcc2","wcc3","stickcricket","8ballpool","carrompool","ludoking","uno","scrabble","chess",
    "checkers","monopoly","risk","battleship","cluedo","pandemic","tickettoride",
    "housie","tambola","braintest","brainout","wordscapes","wordcookies",
    "geometrydash","flappybird","crossyroad","hillclimbracing","hillclimbracing2",
    "realracing3","f1mobile","madskills","mariogolf","tennisclash","archeryking",
    "archero","dungeonsurvivor","dungeonquest","finalfantasy","kingdomhearts",
    "dragonquest","fireemblem","xcom","civilization6","ageofempires","stronghold",
    "commandandconquer","simcity","cities skylines","the sims","the sims4",
    "farming simulator","euro trucksim","bus simulator","train simulator",
    "police simulator","goat simulator","flight simulator",
    "rocketleague","bomberman","worms","supermetroid","kirby","starfox","pexeso",
    "psycho soldier","beyond two souls","heavy rain","detroit becomehuman",
    "littlebigplanet","dreams","granbluefantasy","dragonsdogma","bayonetta",
    "nierautomata","nierreplicant","valheim","satisfactory","factorio","rimworld",
    "slimerancher","overcooked","overcooked2","movingout","castlecrashers",
    "broforce","gangbeasts","humanfallflat","phasmophobia","raft","subnautica",
    "subnauticabelowzero","theforest","sons oftheforest","thelongdark","inside",
    "alanwake","alanwake2","control","quantumbreak","returnal","deathstranding",
    "kenshi","scum","dayz","thedivision","thedivision2","remnant","remnant2",
    "fortnitecreative","robloxdoors","robloxbrookhaven","robloxbedwars","robloxadoptme",
    "robloxjailbreak","robloxarsenal","robloxpiggy","robloxshindo","robloxbladeball",
    "clashmini","clashquest","mariorun","firewatch","gonehome","nightinthewoods",
    "oxenfree","oxenfree2","spiritfarer","sifu","mortalkombat11","gulag","stateofdecay",
    "stateofdecay2","outerwilds","outerworlds","spyro","crashbandicoot","crashteamracing",
    "splatoon","splatoon2","splatoon3","arms","pikmin3","bayonetta3"
)

